name: 'Power BI Pipeline Deploy'
description: 'Deploy Thin PBIX file to through pipeline'
author: 'Nathan Giusti'
inputs:
  files:
    description: 'Files to deploy'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
  
