name: 'Power BI Pipeline Deploy'
description: 'Deploy Thin PBIX file to through pipeline'
author: 'Nathan Giusti & Ravi Yerramilli'
inputs:
  files:
    description: 'Files to deploy'
    required: true
  seperator:
    description: 'seperates files names/paths'
    required: true
    default: ","
  tenant_id:
    description: 'tenant id'
    required : false
  source-stage-order:
    description: 'defines the staging order'
    required: true
    default: '0'
  update-app-in-targetWorkspace:
    description: 'sets the boolean value'
    required: false
    default: 'True'
  allow-purgeData:
    description: 'Should not be needed because this is for reports but fail safe'
    required: true
    default: 'False'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
    - ${{ inputs.seperator }}
    - ${{ inputs.tenant_id}}
    - ${{ inputs.source-stage-order}}
    - ${{ inputs.update-app-in-targetWorkspace}}
    - ${{ inputs.allow-purgeData}}
  
  
  